export const APP_TEXT = {
	forgotPassword: 'Forgot your password?',
	dontHaveAccount: 'Don’t have an account yet?',
	pageNotFound: 'Page not found',
	goBackHome: 'Go back home',
	dontHaveAccess: 'Sorry, but you do not have access to this page',
	done: 'Done',
	balance: 'Balance',
	totalBalance: 'Total balance',
	goal: 'Goal',
	kaif: 'Кайф',
	saved: 'Saved',
	goalName: 'Goal name',
	walletName: 'Wallet name',
	wallet: 'Wallet',
	noData: 'No data',
	walletAddress: 'Wallet address',
	address: 'Address',
	goals: 'Goals',
	deadline: 'Deadline',
	transactionDate: 'Transaction date',
	addDeadline: 'Add deadline',
	currency: 'Currency',
	left: 'Осталось',
	eshe: 'Еще',
	congratulations: 'Поздравляем',
	create: 'Create',
	setEmoji: 'Set emoji',
	portfolioImage: 'Portfolio image',
	fund: 'Fund',
	transfer: 'Transfer',
	withdraw: 'Withdraw',
	continue: 'Continue',
	search: 'Search',
	amount: 'Amount',
	targetAmount: 'Target amount',
	addTargetAmount: 'Add target amount',
	target: 'Target',
	goalAchieved: 'Goal achieved',
	progress: 'Progress',
	transaction: 'Transaction',
	transactions: 'Transactions',
	seeAll: 'See all',
	createdSuccess: 'has been successfully created',
	edit: 'Edit',
	delete: 'Delete',
	disconnectWallet: 'Disconnect wallet',
	disconnect: 'Disconnect',
	share: 'Share',
	update: 'Update',
	save: 'Save',
	name: 'Name',
	deleteGoal: 'Delete goal',
	email: 'Email',
	password: 'Password',
	welcome: 'Welcome',
	logIn: 'Log in',
	logOut: 'Log out',
	signUp: 'Sign up',
	finansy: 'Finansy',

	confirmation: {
		deleteGoal: 'Are you sure you want to delete the',
		deletePortfolio: 'Are you sure you want to delete this portfolio? All transactions will be deleted.',

		disconnectWallet: (portfolioName: string) => {
			return `Are you sure you want to disconnect this wallet from portfolio "${portfolioName}"?`;
		},
	},

	createAccount: 'Create account',
	cancel: 'Cancel',
	confirm: 'Confirm',
	noDate: 'No date',
	customise: 'Customise',
	selectCurrency: 'Select a currency',
	enterTargetValue: 'Enter target value',
	enterWalletName: 'Enter wallet name',
	enterWalletAddress: 'Enter wallet address',
	exchangeRate: 'Exchange rate',
	all: 'All',
	active: 'Active',
	achieved: 'Achieved',
	overdue: 'Overdue',
	portfolio: 'Portfolio',
	portfolioSettings: 'Portfolio settings',
	totalPortfolio: 'Total portfolio',
	period: 'Price change',
	sortBy: 'Sort by',
	by: 'By',
	portfolioName: 'Portfolio name',
	portfolios: 'Portfolios',
	createPortfolio: 'Create portfolio',
	connectWallet: 'Connect wallet',
	connect: 'Connect',
	connectWalletDisclaimer:
		'Finansy requests only view permissions and does not have access to your private keys nor the ability to move your assets',
	connectedWallets: 'Connected wallets',
	connected: 'Connected',
	howItWorks: 'How it works',
	assets: 'Assets',
	walletDetails: 'Wallet details',
	money: 'Money',
	holdings: 'Holdings',
	investedAmount: 'Invested amount',
	marketCap: 'Market cap',
	percentage: 'Percentage',
	alphabetical: 'Alphabetical',

	// Sorting descriptions
	highToLow: 'High to low',
	lowToHigh: 'Low to high',
	aToZ: 'A - Z',
	zToA: 'Z - A',

	statusPopupText: {
		createAccountSuccess: () => (
			<>
				Your account has been <span className='text-primary-violet'>successfully</span> created
			</>
		),
		createAccountError: () => 'Your account has not been created',

		createGoalSuccess: ({name}: any = {}) => `Вы создали цель "${name}"`,
		createGoalError: ({name}: any = {}) => `Some errors occur during creating goal "${name}"`,

		updateGoalSuccess: () => 'Ваша цель была обновлена',
		updateGoalError: () => 'Your goal has not been updated',

		deleteGoalSuccess: () => 'Your goal has been deleted',
		deleteGoalError: () => 'Your goal has not been deleted',

		fundGoalSuccess: ({name, amount}: any = {}) => `Вы пополнили цель "${name}" на ${amount}`,
		fundGoalError: ({name}: any = {}) => `Some errors occur during funding ${name}`,

		withdrawGoalSuccess: ({name, amount}: any = {}) => `Вы вывели с цели "${name}" ${amount} `,
		withdrawGoalError: ({name}: any = {}) => `Some errors occur during withdrawing ${name}`,

		transferGoalSuccess: () => 'Your transfer has been completed',
		transferGoalError: () => 'Some errors occur during transferring',

		connectWalletSuccess: ({name}: any) => `Wallet "${name}" connected`,
		connectWalletError: () => 'Some errors occur wallet connecting',

		createPortfolioSuccess: ({name}: any) => `Portfolio "${name}" created`,
		createPortfolioError: () => 'Some errors occur portfolio creating',

		disconnectWalletSuccess: () => 'Your wallet has been disconnected',
		disconnectWalletError: () => 'Your wallet has not been disconnect',

		updateWalletSuccess: () => 'Your wallet has been updated',
		updateWalletError: () => 'Your wallet has not been updated',

		deletePortfolioSuccess: () => 'Your portfolio has been deleted',
		deletePortfolioError: () => 'Your portfolio has not been deleted',
	},
} as const;
